FROM nvcr.io/nvidia/l4t-base:r32.6.1

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo 

ENV OPENBLAS_CORETYPE=ARMV8

ENV PATH=/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}

RUN apt update
RUN apt install -y tzdata

RUN apt install -y libopencv-dev gcc g++
RUN apt install -y python3-pip
RUN python3 -m pip install -U pip
RUN python3 -m pip install opencv-python

RUN mkdir /models
WORKDIR /models
RUN wget http://pjreddie.com/media/files/yolov3.weights --no-check-certificate
RUN wget http://pjreddie.com/media/files/yolov3-tiny.weights --no-check-certificate

RUN apt install -y git

RUN git config --global http.sslVerify false
WORKDIR /
RUN git clone https://github.com/AlexeyAB/darknet.git
WORKDIR /darknet
COPY ./Makefile ./

RUN make